### ISSUE TITLE
Patient must pay registration fees before clinician administers treatment

### ISSUE THREAD

**Issue by bkirui** [bespokeinteractive/patient-dashboard#8]
The system allows clinicians to administer treatment even without the patient pays for registration fee.
The clinician can search patient in the system and continue administering treatment.

Recommendation: Disable Clinical Notes tab for patients who have not paid registration fee within 24 hrs

**Comment by geoff-wasilwa** [comment]
Tasks:
[ ] Try to recreate the bug on your local machine
[ ] Figure out which controller's are involved
[ ] Modify the logic
[ ] Test to see if bug is resolved and push

**Note**: check if patient has paid when the Clinician select's him/her from the queue and allow the process to go on or _maybe_ redirect back to the queue page with appropriate message 

@bkirui and @ndisha  what would be the appropriate action for patients who are yet to pay?

**Comment by bkirui** [comment]
For patients who are yet to pay, the clinician should be in a position to view only the patient's clinical summary, Lab record, Radiology record, IPD record, Pharmacy record and Patient history,  but should not administer treatment in the Clinical Notes tab.(That's why disabling Clinical Notes Tab was recommended)

N/B: Happens in the case where the nurse has failed to refer patient to specific OPD from triage using the ehms system or the patient has been referred to wrong OPD queue, prompting the clinician to search patient in the entire system.

**Comment by geoff-wasilwa** [comment]
@franqq please take note of what @bkirui has pointed out. Disregard my idea of intercepting the request

**Comment by ndisha** [comment]
@franqq any progress here?

**Comment by franqq** [comment]
Yeah, still working on it

**Comment by ndisha** [comment]
@franqq @geoff-wasilwa tested this out and its working fine. We will revisit the issue of new patients who have not paid on this issue: https://github.com/bespokeinteractive/registration/issues/12 
Closing this out!
